// IF YOU ARE ADDING A NEW MAP, ENSURE YOU DEFINE THE LEVEL TRAITS AND A KEYWORD TO LOAD THEM WITH.
// THE CONFIG USES THE KEYWORD TO LOAD THE ASSIGNED TRAITS.

GLOBAL_LIST_INIT(mining_traits, list(
	"lavaland" = ZTRAITS_LAVALAND,
	"icemoon" = ZTRAITS_ICEMOON,
	"tidalmoon" = ZTRAITS_TIDALMOON,
	"jungle" = ZTRAITS_JUNGLE,
	"rockplanet" = ZTRAITS_ROCKPLANET
))
